


import { Inter } from 'next/font/google';
import './globals.css';
import { ThemeProvider } from '@/contexts/ThemeContext';
import Header from '@/components/Header';
import Script from 'next/script';

const inter = Inter({ subsets: ['latin'] });

export const metadata = {
  title: 'Tech Mobile Insights - AI-Powered Mobile Technology Analysis',
  description: 'Expert AI analysis of mobile technology trends, reviews, and insights.',
  keywords: 'mobile technology,smartphone reviews,tech analysis,AI insights',
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" suppressHydrationWarning>
      <head>
        {/* Google AdSense */}
        <script 
          async 
          src="https://pagead2.googlesyndication.com/pagead/js/adsbygoogle.js?client=ca-pub-5004030673997356"
          crossOrigin="anonymous"
        ></script>
        
        {/* Google Analytics */}
        <script 
          async 
          src="https://www.googletagmanager.com/gtag/js?id=G-R72YF5GZJL"
        ></script>
        <script
          dangerouslySetInnerHTML={{
            __html: `
              window.dataLayer = window.dataLayer || [];
              function gtag(){dataLayer.push(arguments);}
              gtag('js', new Date());
              gtag('config', 'G-R72YF5GZJL');
            `,
          }}
        />
      </head>
      <body className={`${inter.className} min-h-screen transition-colors duration-300`}>
        <ThemeProvider>
          <div className="min-h-screen bg-light-bg dark:bg-dark-bg text-light-text dark:text-dark-text">
            <Header />
            <main className="min-h-screen">
              {children}
            </main>
            <footer className="bg-light-bg dark:bg-dark-bg border-t border-light-border dark:border-dark-border py-12 mt-16">
              <div className="container mx-auto px-4">
                <div className="grid md:grid-cols-4 gap-8">
                  <div className="md:col-span-2">
                    <div className="flex items-center space-x-2 mb-4">
                      <div className="w-8 h-8 bg-brand-primary rounded-lg flex items-center justify-center">
                        <span className="text-white font-bold text-sm">AI</span>
                      </div>
                      <span className="text-xl font-bold text-light-text dark:text-dark-text">Tech Mobile Insights</span>
                    </div>
                    <p className="text-light-text-secondary dark:text-dark-text-secondary mb-4">
                      AI-powered mobile technology analysis providing unique computational insights into the latest trends, devices, and market developments.
                    </p>
                    <p className="text-sm text-light-text-muted dark:text-dark-text-muted">
                      © 2025 Tech Mobile Insights. All content generated by TechAI-1.
                    </p>
                  </div>
                  <div>
                    <h3 className="font-semibold text-light-text dark:text-dark-text mb-4">Categories</h3>
                    <ul className="space-y-2 text-light-text-secondary dark:text-dark-text-secondary">
                      <li><a className="hover:text-brand-primary transition-colors" href="/articles/category/today">Today's News</a></li>
                      <li><a className="hover:text-brand-primary transition-colors" href="/articles/category/current">Current Analysis</a></li>
                      <li><a className="hover:text-brand-primary transition-colors" href="/articles/category/historical">Historical Insights</a></li>
                      <li><a className="hover:text-brand-primary transition-colors" href="/articles/category/trendy">Trending Topics</a></li>
                    </ul>
                  </div>
                  <div>
                    <h3 className="font-semibold text-light-text dark:text-dark-text mb-4">Company</h3>
                    <ul className="space-y-2 text-light-text-secondary dark:text-dark-text-secondary">
                      <li><a className="hover:text-brand-primary transition-colors" href="/articles/category/today">About Us</a></li>
                      <li><a className="hover:text-brand-primary transition-colors" href="/contact">Contact</a></li>
                      <li><a className="hover:text-brand-primary transition-colors" href="/privacy">Privacy Policy</a></li>
                      <li><a className="hover:text-brand-primary transition-colors" href="/terms">Terms of Service</a></li>
                    </ul>
                  </div>
                </div>
              </div>
            </footer>
          </div>
        </ThemeProvider>
      </body>
    </html>
  );
}

