// // frontend/src/components/ConversionBanner.js
// 'use client';
// import Link from 'next/link';

// export default function ConversionBanner({ type = 'mid-article', className = '' }) {
//     const bannerConfigs = {
//         'mid-article': {
//             title: '🤖 Want Your Own AI Content Website Like This?',
//             description: 'This article was automatically generated by our advanced AI system. Get your own automated website with 24/7 content generation, just like TechMobileInsights.',
//             buttonText: 'Get Your AI Website',
//             bgColor: 'bg-gradient-to-r from-blue-50 to-purple-50 dark:from-blue-900/20 dark:to-purple-900/20',
//             borderColor: 'border-blue-200 dark:border-blue-700'
//         },
//         'end-article': {
//             title: '⚡ Scale Your Content Strategy with AI',
//             description: 'Stop writing articles manually. Our system generates high-quality, SEO-optimized content automatically. Perfect for businesses, agencies, and content creators.',
//             buttonText: 'Contact Us for Custom Solution',
//             bgColor: 'bg-gradient-to-r from-green-50 to-blue-50 dark:from-green-900/20 dark:to-blue-900/20',
//             borderColor: 'border-green-200 dark:border-green-700'
//         },
//         'category-showcase': {
//             title: '🚀 Impressed by Our AI Content Quality?',
//             description: 'Every article in this category was created by our automated content generation system. Powered by Gemini 2.5 Flash + OpenAI with intelligent image generation.',
//             buttonText: 'Learn About Our Services',
//             bgColor: 'bg-gradient-to-r from-purple-50 to-pink-50 dark:from-purple-900/20 dark:to-pink-900/20',
//             borderColor: 'border-purple-200 dark:border-purple-700'
//         }
//     };

//     const config = bannerConfigs[type];

//     return (
//         <div className={`my-8 p-6 rounded-xl border-2 ${config.bgColor} ${config.borderColor} ${className}`}>
//             <div className="max-w-4xl mx-auto text-center">
//                 <h3 className="text-xl font-bold text-light-text dark:text-dark-text mb-3">
//                     {config.title}
//                 </h3>
//                 <p className="text-light-text-secondary dark:text-dark-text-secondary mb-6 leading-relaxed">
//                     {config.description}
//                 </p>
//                 <div className="flex flex-col sm:flex-row gap-3 justify-center items-center">
//                     <Link 
//                         href="/contact"
//                         className="px-6 py-3 bg-blue-600 hover:bg-blue-700 text-white font-semibold rounded-lg transition-colors shadow-lg hover:shadow-xl transform hover:-translate-y-0.5 transition-all duration-200"
//                     >
//                         {config.buttonText}
//                     </Link>
//                     <div className="flex items-center text-sm text-light-text-secondary dark:text-dark-text-secondary">
//                         <svg className="w-4 h-4 mr-1" fill="currentColor" viewBox="0 0 20 20">
//                             <path fillRule="evenodd" d="M10 18a8 8 0 100-16 8 8 0 000 16zm3.707-9.293a1 1 0 00-1.414-1.414L9 10.586 7.707 9.293a1 1 0 00-1.414 1.414l2 2a1 1 0 001.414 0l4-4z" clipRule="evenodd" />
//                         </svg>
//                         Free consultation available
//                     </div>
//                 </div>
//             </div>
//         </div>
//     );
// }


// frontend/src/components/ConversionBanner.js
'use client';
import Link from 'next/link';

export default function ConversionBanner({ type = 'mid-article', className = '' }) {
    const bannerConfigs = {
        'mid-article': {
            title: '🤖 Want Your Own AI Content Website Like This?',
            description: 'This article was automatically generated by our advanced AI system. Get your own automated website with 24/7 content generation, just like TechMobileInsights.',
            primaryButton: 'Get Your AI Website',
            secondaryButton: 'Try AI Demo - NO Signup!',
            bgColor: 'bg-gradient-to-r from-blue-50 to-purple-50 dark:from-blue-900/20 dark:to-purple-900/20',
            borderColor: 'border-blue-200 dark:border-blue-700'
        },
        'end-article': {
            title: '⚡ Scale Your Content Strategy with AI',
            description: 'Stop writing articles manually. Our system generates high-quality, SEO-optimized content automatically. Perfect for businesses, agencies, and content creators.',
            primaryButton: 'Contact Us for Custom Solution',
            secondaryButton: 'Test AI Demo - FREE!',
            bgColor: 'bg-gradient-to-r from-green-50 to-blue-50 dark:from-green-900/20 dark:to-blue-900/20',
            borderColor: 'border-green-200 dark:border-green-700'
        },
        'category-showcase': {
            title: '🚀 Impressed by Our AI Content Quality?',
            description: 'Every article in this category was created by our automated content generation system. Powered by Gemini 2.5 Flash + OpenAI with intelligent image generation.',
            primaryButton: 'Learn About Our Services',
            secondaryButton: 'Try AI Generator - No Registration!',
            bgColor: 'bg-gradient-to-r from-purple-50 to-pink-50 dark:from-purple-900/20 dark:to-pink-900/20',
            borderColor: 'border-purple-200 dark:border-purple-700'
        }
    };

    const config = bannerConfigs[type];

    const handleDemoClick = () => {
        window.location.href = '/contact#ai-demo-section';
    };

    return (
        <div className={`my-8 p-6 rounded-xl border-2 ${config.bgColor} ${config.borderColor} ${className}`}>
            <div className="max-w-4xl mx-auto text-center">
                <h3 className="text-xl font-bold text-light-text dark:text-dark-text mb-3">
                    {config.title}
                </h3>
                <p className="text-light-text-secondary dark:text-dark-text-secondary mb-6 leading-relaxed">
                    {config.description}
                </p>
                
                {/* 🎯 Dual Action Buttons with Clear "NO Signup" Messaging */}
                <div className="flex flex-col sm:flex-row gap-4 justify-center items-center mb-4">
                    {/* Primary CTA - Contact */}
                    <Link 
                        href="/contact"
                        className="w-full sm:w-auto px-6 py-3 bg-blue-600 hover:bg-blue-700 text-white font-semibold rounded-lg transition-colors shadow-lg hover:shadow-xl transform hover:-translate-y-0.5 transition-all duration-200 text-center"
                    >
                        {config.primaryButton}
                    </Link>
                    
                    {/* Secondary CTA - Demo with NO Signup Emphasis */}
                    <button
                        onClick={handleDemoClick}
                        className="w-full sm:w-auto px-6 py-3 bg-transparent border-2 border-green-600 text-green-600 dark:text-green-400 hover:bg-green-600 hover:text-white font-semibold rounded-lg transition-all duration-200 transform hover:-translate-y-0.5 relative"
                    >
                        {config.secondaryButton}
                        <div className="absolute -top-2 -right-2 bg-green-500 text-white text-xs px-2 py-1 rounded-full animate-pulse">
                            FREE
                        </div>
                    </button>
                </div>
                
                {/* 🎯 Enhanced Trust Signals with NO Signup Emphasis */}
                <div className="flex flex-col sm:flex-row items-center justify-center gap-4 text-sm text-light-text-secondary dark:text-dark-text-secondary">
                    <div className="flex items-center">
                        <svg className="w-4 h-4 mr-1 text-green-500" fill="currentColor" viewBox="0 0 20 20">
                            <path fillRule="evenodd" d="M10 18a8 8 0 100-16 8 8 0 000 16zm3.707-9.293a1 1 0 00-1.414-1.414L9 10.586 7.707 9.293a1 1 0 00-1.414 1.414l2 2a1 1 0 001.414 0l4-4z" clipRule="evenodd" />
                        </svg>
                        ✨ NO Signup Required for Demo
                    </div>
                    <div className="flex items-center">
                        <svg className="w-4 h-4 mr-1 text-blue-500" fill="currentColor" viewBox="0 0 20 20">
                            <path fillRule="evenodd" d="M3 4a1 1 0 011-1h12a1 1 0 110 2H4a1 1 0 01-1-1zm0 4a1 1 0 011-1h12a1 1 0 110 2H4a1 1 0 01-1-1zm0 4a1 1 0 011-1h12a1 1 0 110 2H4a1 1 0 01-1-1z" clipRule="evenodd" />
                        </svg>
                        🚀 Instant Results in 10 seconds
                    </div>
                    <div className="flex items-center">
                        <svg className="w-4 h-4 mr-1 text-purple-500" fill="currentColor" viewBox="0 0 20 20">
                            <path fillRule="evenodd" d="M2.166 4.999A11.954 11.954 0 0010 1.944 11.954 11.954 0 0017.834 5c.11.65.166 1.32.166 2.001 0 5.225-3.34 9.67-8 11.317C5.34 16.67 2 12.225 2 7c0-.682.057-1.35.166-2.001zm11.541 3.708a1 1 0 00-1.414-1.414L9 10.586 7.707 9.293a1 1 0 00-1.414 1.414l2 2a1 1 0 001.414 0l4-4z" clipRule="evenodd" />
                        </svg>
                        🔒 100% Free & Private
                    </div>
                </div>
            </div>
        </div>
    );
}
