export const metadata = {
  title: 'Privacy Policy - Astrology AI Platform',
  description: 'Privacy policy for Astrology AI Platform and AstroAI Master content generation.',
};

export default function PrivacyPage() {
  return (
    <div className="min-h-screen bg-light-bg dark:bg-dark-bg">
      <div className="container mx-auto px-4 py-8">
        <div className="max-w-4xl mx-auto">
          <header className="text-center mb-12">
            <div className="w-16 h-16 bg-gradient-to-br from-cosmic-600 to-mystical-600 rounded-full flex items-center justify-center mx-auto mb-6">
              <span className="text-white font-bold text-xl">🔒</span>
            </div>
            <h1 className="text-4xl font-bold text-light-text dark:text-dark-text mb-4">Privacy Policy</h1>
            <p className="text-light-text-secondary dark:text-dark-text-secondary">
              <strong>Last updated:</strong> {new Date().toLocaleDateString()}
            </p>
          </header>
          
          <div className="prose prose-lg max-w-none">
            <div className="bg-light-bg-secondary dark:bg-dark-bg-secondary rounded-2xl p-8 border border-light-border dark:border-dark-border mb-8">
              <h2 className="text-2xl font-bold text-light-text dark:text-dark-text mb-4">Our Commitment to Your Privacy</h2>
              <p className="text-light-text-secondary dark:text-dark-text-secondary leading-relaxed">
                At Astrology AI Platform, we respect your cosmic energy and personal information. This privacy policy explains 
                how we collect, use, and protect your information when you interact with AstroAI Master and our services.
              </p>
            </div>

            <section className="mb-8">
              <h2 className="text-2xl font-bold text-light-text dark:text-dark-text mb-4">🔮 Information We Collect</h2>
              <div className="bg-light-bg-secondary dark:bg-dark-bg-secondary rounded-xl p-6 border border-light-border dark:border-dark-border">
                <p className="text-light-text-secondary dark:text-dark-text-secondary mb-4">We collect information you provide directly to us, such as when you:</p>
                <ul className="list-disc list-inside text-light-text-secondary dark:text-dark-text-secondary space-y-2">
                  <li>Contact us through our contact form</li>
                  <li>Subscribe to our newsletter</li>
                  <li>Use our interactive AI demo</li>
                  <li>Browse our astrology articles</li>
                </ul>
              </div>
            </section>
            
            <section className="mb-8">
              <h2 className="text-2xl font-bold text-light-text dark:text-dark-text mb-4">🤖 AI Content Generation</h2>
              <div className="bg-cosmic-50 dark:bg-cosmic-900/20 rounded-xl p-6 border border-cosmic-200 dark:border-cosmic-700">
                <p className="text-light-text-secondary dark:text-dark-text-secondary">
                  Our content is generated by AstroAI Master, our advanced AI agent. We are completely transparent about our 
                  AI-powered approach to astrology content creation. All articles are clearly labeled as AI-generated and 
                  combine ancient Vedic wisdom with modern computational analysis.
                </p>
              </div>
            </section>
            
            <section className="mb-8">
              <h2 className="text-2xl font-bold text-light-text dark:text-dark-text mb-4">🌐 How We Use Your Information</h2>
              <div className="bg-light-bg-secondary dark:bg-dark-bg-secondary rounded-xl p-6 border border-light-border dark:border-dark-border">
                <p className="text-light-text-secondary dark:text-dark-text-secondary mb-4">We use your information to:</p>
                <ul className="list-disc list-inside text-light-text-secondary dark:text-dark-text-secondary space-y-2">
                  <li>Provide personalized astrology content and cosmic guidance</li>
                  <li>Respond to your inquiries and contact requests</li>
                  <li>Improve our AI algorithms and content quality</li>
                  <li>Send you updates about new astrology insights (with your consent)</li>
                  <li>Analyze website usage to enhance user experience</li>
                </ul>
              </div>
            </section>

            <section className="mb-8">
              <h2 className="text-2xl font-bold text-light-text dark:text-dark-text mb-4">🍪 Cookies and Tracking</h2>
              <div className="bg-light-bg-secondary dark:bg-dark-bg-secondary rounded-xl p-6 border border-light-border dark:border-dark-border">
                <p className="text-light-text-secondary dark:text-dark-text-secondary">
                  We use cookies and similar technologies to enhance your experience on our platform. This includes 
                  remembering your theme preferences, language settings, and providing analytics to improve our 
                  astrology content recommendations.
                </p>
              </div>
            </section>

            <section className="mb-8">
              <h2 className="text-2xl font-bold text-light-text dark:text-dark-text mb-4">🔐 Data Security</h2>
              <div className="bg-mystical-50 dark:bg-mystical-900/20 rounded-xl p-6 border border-mystical-200 dark:border-mystical-700">
                <p className="text-light-text-secondary dark:text-dark-text-secondary">
                  We implement appropriate security measures to protect your personal information against unauthorized 
                  access, alteration, disclosure, or destruction. Your cosmic journey with us is protected by industry-standard 
                  security practices.
                </p>
              </div>
            </section>

            <section className="mb-8">
              <h2 className="text-2xl font-bold text-light-text dark:text-dark-text mb-4">🌍 Multi-Language Content</h2>
              <div className="bg-light-bg-secondary dark:bg-dark-bg-secondary rounded-xl p-6 border border-light-border dark:border-dark-border">
                <p className="text-light-text-secondary dark:text-dark-text-secondary">
                  Our platform provides astrology content in multiple languages, including English and हिंदी. 
                  Language preferences are stored locally on your device to enhance your experience.
                </p>
              </div>
            </section>
            
            <section className="mb-8">
              <h2 className="text-2xl font-bold text-light-text dark:text-dark-text mb-4">📞 Contact Information</h2>
              <div className="bg-green-50 dark:bg-green-900/20 rounded-xl p-6 border border-green-200 dark:border-green-700">
                <p className="text-light-text-secondary dark:text-dark-text-secondary mb-4">
                  For privacy-related questions or to exercise your data rights, contact us at:
                </p>
                <div className="flex items-center space-x-2">
                  <span className="text-green-600 dark:text-green-400">✉️</span>
                  <a href="mailto:contact@nakshatrai.com" className="text-green-600 dark:text-green-400 hover:underline">
                    contact@nakshatrai.com
                  </a>
                </div>
              </div>
            </section>

            <section>
              <h2 className="text-2xl font-bold text-light-text dark:text-dark-text mb-4">🔄 Policy Updates</h2>
              <div className="bg-yellow-50 dark:bg-yellow-900/20 rounded-xl p-6 border border-yellow-200 dark:border-yellow-700">
                <p className="text-light-text-secondary dark:text-dark-text-secondary">
                  We may update this privacy policy from time to time. Any changes will be posted on this page with 
                  an updated effective date. We encourage you to review this policy periodically for any cosmic updates.
                </p>
              </div>
            </section>
          </div>
        </div>
      </div>
    </div>
  );
}
