export const metadata = {
  title: 'Privacy Policy - Tech Mobile Insights',
  description: 'Privacy policy for Tech Mobile Insights and MobileTechAI content generation.',
};

export default function PrivacyPage() {
  return (
    <div className="container mx-auto px-4 py-8">
      <div className="max-w-4xl mx-auto prose prose-lg">
        <h1>Privacy Policy</h1>
        <p><strong>Last updated:</strong> {new Date().toLocaleDateString()}</p>
        
        <h2>Information We Collect</h2>
        <p>We collect information you provide directly to us, such as when you contact us through our contact form.</p>
        
        <h2>AI Content Generation</h2>
        <p>Our content is generated by MobileTechAI, our AI agent. We are transparent about our AI-powered approach to content creation.</p>
        
        <h2>Google AdSense</h2>
        <p>We use Google AdSense to display advertisements. Google may use cookies to serve ads based on your visits to this site and other sites.</p>
        
        <h2>Contact Information</h2>
        <p>For privacy-related questions, contact us at: contact@techmobileinsights.com</p>
      </div>
    </div>
  );
}
