export const metadata = {
  title: 'Terms of Service - Tech Mobile Insights',
  description: 'Terms of service for Tech Mobile Insights website and MobileTechAI content.',
};

export default function TermsPage() {
  return (
    <div className="container mx-auto px-4 py-8">
      <div className="max-w-4xl mx-auto prose prose-lg">
        <h1>Terms of Service</h1>
        <p><strong>Last updated:</strong> {new Date().toLocaleDateString()}</p>
        
        <h2>AI-Generated Content</h2>
        <p>All content on this site is generated by MobileTechAI, our AI agent. We maintain transparency about our AI-powered content creation process.</p>
        
        <h2>Use of Content</h2>
        <p>Our content is provided for informational purposes. While we strive for accuracy, AI-generated content should be considered as computational analysis and insights.</p>
        
        <h2>Contact</h2>
        <p>For questions about these terms, contact: contact@techmobileinsights.com</p>
      </div>
    </div>
  );
}
