export const metadata = {
  title: 'Terms of Service - NakshatraAI',
  description: 'Terms of service for NakshatraAI website and AstroAI Master content.',
};

export default function TermsPage() {
  return (
    <div className="min-h-screen bg-light-bg dark:bg-dark-bg">
      <div className="container mx-auto px-4 py-8">
        <div className="max-w-4xl mx-auto">
          <header className="text-center mb-12">
            <div className="w-16 h-16 bg-gradient-to-br from-cosmic-600 to-mystical-600 rounded-full flex items-center justify-center mx-auto mb-6">
              <span className="text-white font-bold text-xl">📜</span>
            </div>
            <h1 className="text-4xl font-bold text-light-text dark:text-dark-text mb-4">Terms of Service</h1>
            <p className="text-light-text-secondary dark:text-dark-text-secondary">
              <strong>Last updated:</strong> {new Date().toLocaleDateString()}
            </p>
          </header>
          
          <div className="prose prose-lg max-w-none">
            <div className="bg-light-bg-secondary dark:bg-dark-bg-secondary rounded-2xl p-8 border border-light-border dark:border-dark-border mb-8">
              <h2 className="text-2xl font-bold text-light-text dark:text-dark-text mb-4">Welcome to NakshatraAI</h2>
              <p className="text-light-text-secondary dark:text-dark-text-secondary leading-relaxed">
                These terms of service govern your use of our platform and the cosmic guidance provided by AstroAI Master. 
                By accessing our website, you agree to these terms and embark on a journey of AI-powered astrological discovery.
              </p>
            </div>

            <section className="mb-8">
              <h2 className="text-2xl font-bold text-light-text dark:text-dark-text mb-4">🤖 AI-Generated Content</h2>
              <div className="bg-cosmic-50 dark:bg-cosmic-900/20 rounded-xl p-6 border border-cosmic-200 dark:border-cosmic-700">
                <p className="text-light-text-secondary dark:text-dark-text-secondary mb-4">
                  All content on this site is generated by AstroAI Master, our advanced AI agent. We maintain complete 
                  transparency about our AI-powered content creation process. Key points:
                </p>
                <ul className="list-disc list-inside text-light-text-secondary dark:text-dark-text-secondary space-y-2">
                  <li>Content combines ancient Vedic wisdom with modern computational analysis</li>
                  <li>AI-generated articles are clearly labeled and attributed</li>
                  <li>Content is created for educational and entertainment purposes</li>
                  <li>We strive for cultural sensitivity and accuracy in our astrological content</li>
                </ul>
              </div>
            </section>
            
            <section className="mb-8">
              <h2 className="text-2xl font-bold text-light-text dark:text-dark-text mb-4">🔮 Use of Astrological Content</h2>
              <div className="bg-light-bg-secondary dark:bg-dark-bg-secondary rounded-xl p-6 border border-light-border dark:border-dark-border">
                <p className="text-light-text-secondary dark:text-dark-text-secondary mb-4">
                  Our astrological content is provided for informational and entertainment purposes. Please understand:
                </p>
                <ul className="list-disc list-inside text-light-text-secondary dark:text-dark-text-secondary space-y-2">
                  <li>AI-generated predictions should be considered as computational analysis and insights</li>
                  <li>Content should not replace professional advice for important life decisions</li>
                  <li>We respect traditional astrological practices while offering modern AI perspectives</li>
                  <li>Individual results and interpretations may vary</li>
                </ul>
              </div>
            </section>

            <section className="mb-8">
              <h2 className="text-2xl font-bold text-light-text dark:text-dark-text mb-4">🌍 Multi-Language Services</h2>
              <div className="bg-mystical-50 dark:bg-mystical-900/20 rounded-xl p-6 border border-mystical-200 dark:border-mystical-700">
                <p className="text-light-text-secondary dark:text-dark-text-secondary">
                  We provide astrology content in multiple languages, including English and हिंदी. Our AI system 
                  maintains cultural sensitivity and authenticity across different languages while respecting 
                  traditional astrological terminology and concepts.
                </p>
              </div>
            </section>

            <section className="mb-8">
              <h2 className="text-2xl font-bold text-light-text dark:text-dark-text mb-4">🚫 Prohibited Uses</h2>
              <div className="bg-red-50 dark:bg-red-900/20 rounded-xl p-6 border border-red-200 dark:border-red-700">
                <p className="text-light-text-secondary dark:text-dark-text-secondary mb-4">You may not:</p>
                <ul className="list-disc list-inside text-light-text-secondary dark:text-dark-text-secondary space-y-2">
                  <li>Copy or redistribute our AI-generated content without permission</li>
                  <li>Use our platform for harmful or illegal activities</li>
                  <li>Attempt to reverse-engineer our AI algorithms</li>
                  <li>Spam or misuse our contact forms or services</li>
                  <li>Violate any applicable laws or regulations</li>
                </ul>
              </div>
            </section>

            <section className="mb-8">
              <h2 className="text-2xl font-bold text-light-text dark:text-dark-text mb-4">🔒 Intellectual Property</h2>
              <div className="bg-light-bg-secondary dark:bg-dark-bg-secondary rounded-xl p-6 border border-light-border dark:border-dark-border">
                <p className="text-light-text-secondary dark:text-dark-text-secondary">
                  All content generated by AstroAI Master, including articles, predictions, and insights, is protected 
                  by intellectual property rights. While we draw inspiration from ancient texts and traditional astrology, 
                  our AI-generated interpretations and presentations are original works.
                </p>
              </div>
            </section>

            <section className="mb-8">
              <h2 className="text-2xl font-bold text-light-text dark:text-dark-text mb-4">⚠️ Disclaimers</h2>
              <div className="bg-yellow-50 dark:bg-yellow-900/20 rounded-xl p-6 border border-yellow-200 dark:border-yellow-700">
                <p className="text-light-text-secondary dark:text-dark-text-secondary mb-4">Important disclaimers:</p>
                <ul className="list-disc list-inside text-light-text-secondary dark:text-dark-text-secondary space-y-2">
                  <li>Astrological content is for entertainment and educational purposes</li>
                  <li>We do not guarantee the accuracy of predictions or cosmic insights</li>
                  <li>Our AI system continuously learns and improves its astrological analysis</li>
                  <li>Individual cosmic experiences may vary based on personal circumstances</li>
                </ul>
              </div>
            </section>

            <section className="mb-8">
              <h2 className="text-2xl font-bold text-light-text dark:text-dark-text mb-4">🔄 Service Modifications</h2>
              <div className="bg-light-bg-secondary dark:bg-dark-bg-secondary rounded-xl p-6 border border-light-border dark:border-dark-border">
                <p className="text-light-text-secondary dark:text-dark-text-secondary">
                  We reserve the right to modify, suspend, or discontinue any part of our service at any time. 
                  We may also update these terms to reflect changes in our AI technology or astrological methodologies.
                </p>
              </div>
            </section>
            
            <section>
              <h2 className="text-2xl font-bold text-light-text dark:text-dark-text mb-4">📞 Contact</h2>
              <div className="bg-green-50 dark:bg-green-900/20 rounded-xl p-6 border border-green-200 dark:border-green-700">
                <p className="text-light-text-secondary dark:text-dark-text-secondary mb-4">
                  For questions about these terms or our astrological services, contact:
                </p>
                <div className="flex items-center space-x-2">
                  <span className="text-green-600 dark:text-green-400">✉️</span>
                  <a href="mailto:contact@nakshatrai.com" className="text-green-600 dark:text-green-400 hover:underline">
                    contact@nakshatrai.com
                  </a>
                </div>
              </div>
            </section>
          </div>
        </div>
      </div>
    </div>
  );
}
